using System.IO;
using NUnit.Framework;
using RudyAtkinson.AGSI.Editor;
using RudyAtkinson.AGSI.Runtime;
using UnityEngine;

namespace RudyAtkinson.AGSI.Tests
{
    public class AutoGeneratedSignalInstallerTest
    {
        [Test]
        public void AGSIEnabledAutoGenerateTest()
        {
            var settings = SignalInstallerCodeGenerationSettings.GetSettingsFromResources();
            
            SignalInstallerCodeGeneration.FindSignalsAndGenerateCode(settings);

            var path = Path.Combine(Application.dataPath, settings.InstallerPath, settings.InstallerClassName + ".cs");
            var installerText = File.ReadAllText(path);
            
            var actual = "using Zenject;\nusing RudyAtkinson.AGSI.Tests;\n\npublic class AutoGeneratedSignalInstaller : MonoInstaller \n{ \n     public override void InstallBindings()\n     {\n          SignalBusInstaller.Install(Container);\n          Container.DeclareSignal<ASignal>();\n          Container.DeclareSignal<BSignal>();\n     }\n}";
            Assert.AreEqual(installerText, actual);
        }
    }

    public class ASignal: IAutoGeneratedSignal
    {
        
    }

    public class BSignal: IAutoGeneratedSignal
    {
        
    }
}
