name: Acquire activation file

on:
  workflow_dispatch:
  push:
    branches:
      - ci/activation
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2022.3.17f1
          - 2021.1.4f1
          - 2020.3.5f1
          - 2019.4.25f1
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2.2.0
        with:
          unityVersion: ${{ matrix.unityVersion }}
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}        