name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-unity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2022.3.17f1
          - 2021.1.4f1
          - 2020.3.5f1
          - 2019.4.25f1
    steps:
      - uses: actions/checkout@v2

      - uses: game-ci/unity-test-runner@v2.0-alpha-4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
      - uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: artifacts